default_language_version:
  python: python3
repos:
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        args: ["--preview", "--enable-unstable-feature", "string_processing"]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.8
    hooks:
      - id: ruff
        args: ["--fix", "--exit-non-zero-on-fix"]
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: poetry run mypy src
        language: system
        types: [python]
        pass_filenames: false
        files: ^src/
      - id: bandit
        name: bandit
        entry: poetry run bandit -r src -ll
        language: system
        types: [python]
        pass_filenames: false
