[project]
name = "service-ambitions"
version = "0.1.0"
description = "Command-line tool for generating service ambitions using a chat model."
readme = "README.md"
authors = [
    {name = "Jolyon Suthers",email = "201621+fenrick@users.noreply.github.com"}
]
requires-python = ">= 3.11,<4"
dependencies = [
"openai" ,
"langchain" ,
"langchain-core" ,
"langchain-openai",
"python-dotenv",
]

[tool.poetry.group.dev.dependencies]
black = "*"
ruff = "*"
mypy = "*"
bandit = "*"
"pip-audit" = "*"
pytest = "*"
isort = "*"
flake8 = "*"
flake8-bugbear = "*"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
package-mode = false

[tool.black]
line-length = 88
target-version = ["py313"]

[tool.ruff]
line-length = 88
target-version = "py313"

[tool.ruff.lint]
select = ["E", "F", "I"]

[tool.isort]
profile = "black"
