name: CI

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install black ruff pytest mypy bandit pip-audit
      - name: Check formatting
        run: black --check .
      - name: Lint
        run: ruff check .
      - name: Type check
        run: mypy .
      - name: Security scan
        run: bandit -r . -ll
      - name: Dependency audit
        run: pip-audit
      - name: Run tests
        run: pytest
