name: CI

on:
  push:
    branches: ["main", "master"]
  pull_request:

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install black ruff pytest
      - name: Check formatting
        run: black --check .
      - name: Lint
        run: ruff check .
      - name: Run tests
        run: pytest
