name: Docs

on:
  push:
    branches: [main]
    paths:
      - 'docs/**'
      - '**/*.md'
  pull_request:
    branches: [main]
    paths:
      - 'docs/**'
      - '**/*.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: read-all
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Install Poetry
        run: pipx install poetry
      - uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version: '3.11'
          cache: 'poetry'
      - name: Install dependencies
        run: poetry install --no-interaction --no-root --with docs
      - name: Build documentation site
        run: poetry run mkdocs build --strict
