name: Nightly

on:
  schedule:
    - cron: '0 16 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        py: ['3.10', '3.11', '3.12']
    permissions: read-all
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: ${{ matrix.py }}
          cache: 'pip'
      - name: Install dependencies
        run: pip install -e .[dev,security]
      - name: Pytest
        run: pytest -q
      - name: Install audit tools
        run: pip install pip-audit safety
      - name: pip-audit
        run: pip-audit -r requirements.txt || true
