name: Nightly

on:
  schedule:
    - cron: '0 16 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        py: ['3.10', '3.11', '3.12']
    permissions: read-all
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Install Poetry
        run: |
          pipx install poetry
          pipx inject poetry poetry-plugin-export
      - uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version: ${{ matrix.py }}
          cache: 'poetry'
      - name: Install dependencies
        run: poetry install --no-interaction
      - name: Mypy --strict
        run: poetry run mypy --strict src tests
      - name: Pytest
        run: poetry run pytest -q
      - name: pip-audit
        run: |
          poetry export --format=requirements.txt --without-hashes --output=requirements.txt
          poetry run pip-audit -r requirements.txt || true
      - name: Safety
        run: poetry run safety check --full-report || true
